### PR TITLE
ffmpeg: Bump PKG_RELEASE for CirclCI testing

### PR DESCRIPTION
**Pull request by thess**
Oldie but goodie - never, ever built on Travis

### CODE REVIEW

**Comment by thess** [comment]
Was the the right place to test ?? Nothing seemed to happen

**Comment by champtar** [comment]
@thess can you rebase on my master, so we are sure you have circleci conf

**Comment by thess** [comment]
@champtar - duh! Got it.

**Comment by champtar** [comment]
compilation failed, but you have the logs :D
https://circleci.com/gh/champtar/packages/72#artifacts
(yes there is a bug when you are not logged in you don't see the artifacts tab but it's accessible)
https://72-20461085-gh.circle-artifacts.com/0/root/build_dir/logs/package/feeds/packages/ffmpeg/full/compile.txt

I'll try to compile your PR and add everything that is missing in the docker image

**Comment by champtar** [comment]
I've tried to build it in the docker container, shine is never built, I think dependency doesn't work properly
```
 DEPENDS+= +alsa-lib +PACKAGE_libopus:libopus
 ifeq ($(CONFIG_SOFT_FLOAT),y)
        DEPENDS+= +PACKAGE_shine:shine
 else
        DEPENDS+= +PACKAGE_lame-lib:lame-lib +PACKAGE_libx264:libx264 +PACKAGE_fdk-aac:fdk-aac
 endif
```
I think you need to try something like
```
+(SOFT_FLOAT&&PACKAGE_shine):shine
```

**Comment by thess** [comment]
... Testing config changes to appease CI builds

**Comment by champtar** [comment]
@thess the problem is the "if" that is not evaluated in some cases
try my syntax

**Comment by thess** [comment]
@champtar - IIRC, I got a recursive dependency error.

**Comment by thess** [comment]
Tada! Minor change to defer config var test to 2nd eval pass. The interaction of CONFIG var definitions and evaluation is subtly different in private build tree (git clone), SDK targeted builds and buildbot ALL builds.

**Pull request closed without merging**
